[build]
  publish = "."
  functions = "netlify/functions"

# Cache the aggregator result at CDN edge for 10 minutes
[[headers]]
  for = "/.netlify/functions/fetchFeeds"
  [headers.values]
    Cache-Control = "public, max-age=600"
