[build]
  publish = "."
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  included_files = ["data/feeds.json", "data/allow_full_domains.json"]

[[redirects]]
  from = "/api/rss"
  to = "/.netlify/functions/rss"
  status = 200
