[build]
  publish = "."
  functions = "netlify/functions"

# Serve /sitemap.xml from the function (Google likes this path)
[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
  force = true
