[build]
  command = ""          # no build step for static site
  publish = "."

[functions]
  directory = "netlify/functions"   # location of serverless functions
  node_bundler = "esbuild"          # makes sure deps like rss-parser are bundled

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
